### ISSUE TITLE
a bunch of errors with v1.2.0 "migrate" which looks like version skew of some sort

### ISSUE THREAD

**Issue by vielmetti** [kstrauser/frozenbbs#2]
Super interested in progress here! I love the idea of doing a BBS
design that's specifically tuned to the limits of Meshtastic.

I'm trying to build and test v1.2.0 from scratch, but when I follow the `justfile` to do `just db_migrate` it builds a v1.1.0 version of something and then spits out lots of errors

gist at https://gist.github.com/vielmetti/d2f7df6ecccd577c1da9228ed5d24a3b

the start of it reads

```
mkdir -p $(dirname "`cargo run config db-path`")
   Compiling frozenbbs v1.1.0 (/Users/emv/src/github.com/kstrauser/frozenbbs)
error[E0432]: unresolved import `super::schema::board_states`
 --> src/db/board_states.rs:2:20
  |
2 | use super::schema::board_states::{dsl, table};
  |                    ^^^^^^^^^^^^ could not find `board_states` in `schema`
```

```
> git status
HEAD detached at v1.2.0
```

just a bit puzzled by all this, especially the v1.1.0 reference in the error log.

**Comment by kstrauser** [comment]
The version bit is a mistake. I just forgot to update Cargo.toml.

The other errors are something I need to straighten up ASAP. Here's what happens:

- Way up up in that wall of errors, I bet there's run of `cargo run config db-path` that had output like:

```
thread 'main' panicked at src/lib.rs:89:5:
Unable to read the config file at "/Users/kirk/.config/frozenbbs/config.toml"

Create a new file with values like:

=======
bbs_name = "Frozen BBS❅"
my_id = "!cafeb33d"
db_path = "/Users/kirk/.local/share/frozenbbs/frozenbbs.db"
serial_device = "/dev/ttyUSB0"
sysops = []
public_channel = 0
ad_text = "I'm running a BBS on this node. DM me to get started!"
=======
```
- It's looking for a config file that doesn't exist yet. When that fails, the failed DB migration generates a new, empty `src/db/schema.rs`.
- Now future runs of anything will get that wall of error text.

I'll work on that. Config handling in general needs some TLC. The Makefile could be more defensive here, too.

Here's how you can recover:

- Create a new `~/.config/frozenbbs/config.toml` file with the contents from the error message.
- Run `git restore src/db/schema.rs` to fix the schema file.
- Run `just db_migrate` again.

That should get you running.

**Comment by kstrauser** [comment]
This should be a lot cleaner in the new v1.3.0 release I just pushed. Relevant to this issue, it has much better support for default configs. I cloned this into a clean directory, deleted my existing config and DB directories, and ran the setup instructions from scratch successfully.
