### ISSUE TITLE
v1.3.2 README refers to `just db_init` which I think is now `just db_fixture`

### ISSUE THREAD

**Issue by vielmetti** [kstrauser/frozenbbs#3]
I think the code got ahead of the README and the optional `just db_init` to create some test data looks like it's been subsumed  by `just db_fixture`.

Otherwise a fresh install went just fine according to instructions with everything from #2 resolved.

**Comment by kstrauser** [comment]
Good catch! I fixed it in 6ffaabf96589aa55b6cb1ab1f33f692da1239782.
